// <auto-generated />
namespace TravelAgency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewImageAttr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewImageAttr));
        
        string IMigrationMetadata.Id
        {
            get { return "201902011108079_NewImageAttr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
